// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dan6erbond/revline/ent/modidea"
	"github.com/Dan6erbond/revline/ent/predicate"
)

// ModIdeaDelete is the builder for deleting a ModIdea entity.
type ModIdeaDelete struct {
	config
	hooks    []Hook
	mutation *ModIdeaMutation
}

// Where appends a list predicates to the ModIdeaDelete builder.
func (mid *ModIdeaDelete) Where(ps ...predicate.ModIdea) *ModIdeaDelete {
	mid.mutation.Where(ps...)
	return mid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mid *ModIdeaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mid.sqlExec, mid.mutation, mid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mid *ModIdeaDelete) ExecX(ctx context.Context) int {
	n, err := mid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mid *ModIdeaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modidea.Table, sqlgraph.NewFieldSpec(modidea.FieldID, field.TypeUUID))
	if ps := mid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mid.mutation.done = true
	return affected, err
}

// ModIdeaDeleteOne is the builder for deleting a single ModIdea entity.
type ModIdeaDeleteOne struct {
	mid *ModIdeaDelete
}

// Where appends a list predicates to the ModIdeaDelete builder.
func (mido *ModIdeaDeleteOne) Where(ps ...predicate.ModIdea) *ModIdeaDeleteOne {
	mido.mid.mutation.Where(ps...)
	return mido
}

// Exec executes the deletion query.
func (mido *ModIdeaDeleteOne) Exec(ctx context.Context) error {
	n, err := mido.mid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modidea.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mido *ModIdeaDeleteOne) ExecX(ctx context.Context) {
	if err := mido.Exec(ctx); err != nil {
		panic(err)
	}
}
