// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dan6erbond/revline/ent/car"
	"github.com/Dan6erbond/revline/ent/modidea"
	"github.com/Dan6erbond/revline/ent/modproductoption"
	"github.com/Dan6erbond/revline/ent/task"
	"github.com/google/uuid"
)

// ModIdeaCreate is the builder for creating a ModIdea entity.
type ModIdeaCreate struct {
	config
	mutation *ModIdeaMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (mic *ModIdeaCreate) SetCreateTime(t time.Time) *ModIdeaCreate {
	mic.mutation.SetCreateTime(t)
	return mic
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mic *ModIdeaCreate) SetNillableCreateTime(t *time.Time) *ModIdeaCreate {
	if t != nil {
		mic.SetCreateTime(*t)
	}
	return mic
}

// SetUpdateTime sets the "update_time" field.
func (mic *ModIdeaCreate) SetUpdateTime(t time.Time) *ModIdeaCreate {
	mic.mutation.SetUpdateTime(t)
	return mic
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (mic *ModIdeaCreate) SetNillableUpdateTime(t *time.Time) *ModIdeaCreate {
	if t != nil {
		mic.SetUpdateTime(*t)
	}
	return mic
}

// SetTitle sets the "title" field.
func (mic *ModIdeaCreate) SetTitle(s string) *ModIdeaCreate {
	mic.mutation.SetTitle(s)
	return mic
}

// SetCategory sets the "category" field.
func (mic *ModIdeaCreate) SetCategory(m modidea.Category) *ModIdeaCreate {
	mic.mutation.SetCategory(m)
	return mic
}

// SetDescription sets the "description" field.
func (mic *ModIdeaCreate) SetDescription(s string) *ModIdeaCreate {
	mic.mutation.SetDescription(s)
	return mic
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mic *ModIdeaCreate) SetNillableDescription(s *string) *ModIdeaCreate {
	if s != nil {
		mic.SetDescription(*s)
	}
	return mic
}

// SetStage sets the "stage" field.
func (mic *ModIdeaCreate) SetStage(s string) *ModIdeaCreate {
	mic.mutation.SetStage(s)
	return mic
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (mic *ModIdeaCreate) SetNillableStage(s *string) *ModIdeaCreate {
	if s != nil {
		mic.SetStage(*s)
	}
	return mic
}

// SetID sets the "id" field.
func (mic *ModIdeaCreate) SetID(u uuid.UUID) *ModIdeaCreate {
	mic.mutation.SetID(u)
	return mic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mic *ModIdeaCreate) SetNillableID(u *uuid.UUID) *ModIdeaCreate {
	if u != nil {
		mic.SetID(*u)
	}
	return mic
}

// SetCarID sets the "car" edge to the Car entity by ID.
func (mic *ModIdeaCreate) SetCarID(id uuid.UUID) *ModIdeaCreate {
	mic.mutation.SetCarID(id)
	return mic
}

// SetCar sets the "car" edge to the Car entity.
func (mic *ModIdeaCreate) SetCar(c *Car) *ModIdeaCreate {
	return mic.SetCarID(c.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (mic *ModIdeaCreate) AddTaskIDs(ids ...uuid.UUID) *ModIdeaCreate {
	mic.mutation.AddTaskIDs(ids...)
	return mic
}

// AddTasks adds the "tasks" edges to the Task entity.
func (mic *ModIdeaCreate) AddTasks(t ...*Task) *ModIdeaCreate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mic.AddTaskIDs(ids...)
}

// AddProductOptionIDs adds the "product_options" edge to the ModProductOption entity by IDs.
func (mic *ModIdeaCreate) AddProductOptionIDs(ids ...uuid.UUID) *ModIdeaCreate {
	mic.mutation.AddProductOptionIDs(ids...)
	return mic
}

// AddProductOptions adds the "product_options" edges to the ModProductOption entity.
func (mic *ModIdeaCreate) AddProductOptions(m ...*ModProductOption) *ModIdeaCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mic.AddProductOptionIDs(ids...)
}

// Mutation returns the ModIdeaMutation object of the builder.
func (mic *ModIdeaCreate) Mutation() *ModIdeaMutation {
	return mic.mutation
}

// Save creates the ModIdea in the database.
func (mic *ModIdeaCreate) Save(ctx context.Context) (*ModIdea, error) {
	mic.defaults()
	return withHooks(ctx, mic.sqlSave, mic.mutation, mic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mic *ModIdeaCreate) SaveX(ctx context.Context) *ModIdea {
	v, err := mic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mic *ModIdeaCreate) Exec(ctx context.Context) error {
	_, err := mic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mic *ModIdeaCreate) ExecX(ctx context.Context) {
	if err := mic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mic *ModIdeaCreate) defaults() {
	if _, ok := mic.mutation.CreateTime(); !ok {
		v := modidea.DefaultCreateTime()
		mic.mutation.SetCreateTime(v)
	}
	if _, ok := mic.mutation.UpdateTime(); !ok {
		v := modidea.DefaultUpdateTime()
		mic.mutation.SetUpdateTime(v)
	}
	if _, ok := mic.mutation.ID(); !ok {
		v := modidea.DefaultID()
		mic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mic *ModIdeaCreate) check() error {
	if _, ok := mic.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "ModIdea.create_time"`)}
	}
	if _, ok := mic.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "ModIdea.update_time"`)}
	}
	if _, ok := mic.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ModIdea.title"`)}
	}
	if _, ok := mic.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ModIdea.category"`)}
	}
	if v, ok := mic.mutation.Category(); ok {
		if err := modidea.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ModIdea.category": %w`, err)}
		}
	}
	if len(mic.mutation.CarIDs()) == 0 {
		return &ValidationError{Name: "car", err: errors.New(`ent: missing required edge "ModIdea.car"`)}
	}
	return nil
}

func (mic *ModIdeaCreate) sqlSave(ctx context.Context) (*ModIdea, error) {
	if err := mic.check(); err != nil {
		return nil, err
	}
	_node, _spec := mic.createSpec()
	if err := sqlgraph.CreateNode(ctx, mic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mic.mutation.id = &_node.ID
	mic.mutation.done = true
	return _node, nil
}

func (mic *ModIdeaCreate) createSpec() (*ModIdea, *sqlgraph.CreateSpec) {
	var (
		_node = &ModIdea{config: mic.config}
		_spec = sqlgraph.NewCreateSpec(modidea.Table, sqlgraph.NewFieldSpec(modidea.FieldID, field.TypeUUID))
	)
	if id, ok := mic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mic.mutation.CreateTime(); ok {
		_spec.SetField(modidea.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := mic.mutation.UpdateTime(); ok {
		_spec.SetField(modidea.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := mic.mutation.Title(); ok {
		_spec.SetField(modidea.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mic.mutation.Category(); ok {
		_spec.SetField(modidea.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := mic.mutation.Description(); ok {
		_spec.SetField(modidea.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := mic.mutation.Stage(); ok {
		_spec.SetField(modidea.FieldStage, field.TypeString, value)
		_node.Stage = &value
	}
	if nodes := mic.mutation.CarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modidea.CarTable,
			Columns: []string{modidea.CarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(car.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.car_mod_ideas = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mic.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   modidea.TasksTable,
			Columns: modidea.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mic.mutation.ProductOptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modidea.ProductOptionsTable,
			Columns: []string{modidea.ProductOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modproductoption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModIdeaCreateBulk is the builder for creating many ModIdea entities in bulk.
type ModIdeaCreateBulk struct {
	config
	err      error
	builders []*ModIdeaCreate
}

// Save creates the ModIdea entities in the database.
func (micb *ModIdeaCreateBulk) Save(ctx context.Context) ([]*ModIdea, error) {
	if micb.err != nil {
		return nil, micb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(micb.builders))
	nodes := make([]*ModIdea, len(micb.builders))
	mutators := make([]Mutator, len(micb.builders))
	for i := range micb.builders {
		func(i int, root context.Context) {
			builder := micb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModIdeaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, micb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, micb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, micb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (micb *ModIdeaCreateBulk) SaveX(ctx context.Context) []*ModIdea {
	v, err := micb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (micb *ModIdeaCreateBulk) Exec(ctx context.Context) error {
	_, err := micb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (micb *ModIdeaCreateBulk) ExecX(ctx context.Context) {
	if err := micb.Exec(ctx); err != nil {
		panic(err)
	}
}
