package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

// Car returns CarResolver implementation.
func (r *Resolver) Car() CarResolver { return &carResolver{r} }

// Media returns MediaResolver implementation.
func (r *Resolver) Media() MediaResolver { return &mediaResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

// CreateFuelUpInput returns CreateFuelUpInputResolver implementation.
func (r *Resolver) CreateFuelUpInput() CreateFuelUpInputResolver {
	return &createFuelUpInputResolver{r}
}

// CreateServiceLogInput returns CreateServiceLogInputResolver implementation.
func (r *Resolver) CreateServiceLogInput() CreateServiceLogInputResolver {
	return &createServiceLogInputResolver{r}
}

type carResolver struct{ *Resolver }
type mediaResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
type createFuelUpInputResolver struct{ *Resolver }
type createServiceLogInputResolver struct{ *Resolver }
