// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// DragResult is the predicate function for dragresult builders.
type DragResult func(*sql.Selector)

// DragSession is the predicate function for dragsession builders.
type DragSession func(*sql.Selector)

// FuelUp is the predicate function for fuelup builders.
type FuelUp func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// OdometerReading is the predicate function for odometerreading builders.
type OdometerReading func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// ServiceItem is the predicate function for serviceitem builders.
type ServiceItem func(*sql.Selector)

// ServiceLog is the predicate function for servicelog builders.
type ServiceLog func(*sql.Selector)

// ServiceSchedule is the predicate function for serviceschedule builders.
type ServiceSchedule func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
