// Code generated by ent, DO NOT EDIT.

package modproductoption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modproductoption type in the database.
	Label = "mod_product_option"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldVendor holds the string denoting the vendor field in the database.
	FieldVendor = "vendor"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldPros holds the string denoting the pros field in the database.
	FieldPros = "pros"
	// FieldCons holds the string denoting the cons field in the database.
	FieldCons = "cons"
	// FieldSpecs holds the string denoting the specs field in the database.
	FieldSpecs = "specs"
	// EdgeIdea holds the string denoting the idea edge name in mutations.
	EdgeIdea = "idea"
	// Table holds the table name of the modproductoption in the database.
	Table = "mod_product_options"
	// IdeaTable is the table that holds the idea relation/edge.
	IdeaTable = "mod_product_options"
	// IdeaInverseTable is the table name for the ModIdea entity.
	// It exists in this package in order to avoid circular dependency with the "modidea" package.
	IdeaInverseTable = "mod_ideas"
	// IdeaColumn is the table column denoting the idea relation/edge.
	IdeaColumn = "mod_idea_product_options"
)

// Columns holds all SQL columns for modproductoption fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldVendor,
	FieldName,
	FieldLink,
	FieldPrice,
	FieldNotes,
	FieldPros,
	FieldCons,
	FieldSpecs,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "mod_product_options"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"mod_idea_product_options",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ModProductOption queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByVendor orders the results by the vendor field.
func ByVendor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVendor, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLink orders the results by the link field.
func ByLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLink, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByIdeaField orders the results by idea field.
func ByIdeaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIdeaStep(), sql.OrderByField(field, opts...))
	}
}
func newIdeaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IdeaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IdeaTable, IdeaColumn),
	)
}
