// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Dan6erbond/revline/ent"
)

type UpcomingService struct {
	Schedule    *ent.ServiceSchedule `json:"schedule"`
	NextDueKm   *float64             `json:"nextDueKm,omitempty"`
	NextDueDate *time.Time           `json:"nextDueDate,omitempty"`
}

type UploadMediaResult struct {
	Media     *ent.Media `json:"media"`
	UploadURL string     `json:"uploadUrl"`
}

type UploadProfilePictureInput struct {
	Picture *graphql.Upload `json:"picture,omitempty"`
}
